[build]
    command = "yarn build"
    publish = "dist"

[build.environment]
    NODE_VERSION = "14"

[context.production.environment]
    ELEVENTY_ENV = "production"

[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"
        X-Content-Type-Options = "nosniff"
        Referrer-Policy= "no-referrer-when-downgrade"

# [[redirects]]
#     from = "https://mikrouli.netlify.com/*"
#     to = "https://mikrouli.nl/:splat
#     status = 301
#     force = true

[[redirects]]
    from = "*"
    to = "/404"
    status = 404
